const chapters=Array.from({length:21},(_,i)=>({number:i+1,title:i===0?'Donde empezó todo':i===11?'Nuestro primer año':i===20?'Todo lo que construimos':`Nuestro mes ${i+1}`,date:i===0?'05 · 01 · 24':`MES ${String(i+1).padStart(2,'0')}`,photos:[1,2,3].map(n=>({src:`images/mes${i+1}/foto${n}.jpg`,note:n===1?'Aquí puedes escribir lo que recuerdas de esta foto, con tus propias palabras.':n===2?'Una foto, una historia y algo que solo ustedes dos entienden.':'De esos momentos que merecen quedarse guardados para siempre.'}))}));
// Cambia los títulos y artistas aquí; conserva las rutas de tus archivos.
const songs=Array.from({length:21},(_,i)=>({
  title:`Canción del mes ${i+1}`,
  artist:`Mes ${i+1} · Brian & Noelia`,
  src:`musica/mes${i+1}/cancion1.mp3`,
  icon:String(i+1).padStart(2,'0')
}));
const secretSong={title:'Nuestro secreto',artist:'Canción desbloqueada',src:'musica/regalo/sorpresa.mp3',icon:'🎁',secret:true},$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let chapterIndex=0,photoIndex=0,songIndex=0,isPlaying=false,shuffle=false,repeatMode=0;const audio=$('#audio-element');
function createMonthCards(){chapters.forEach((ch,i)=>{const b=document.createElement('button');b.className='month-card'+(i?'':' active');b.innerHTML=`<span class="mini-collage"><i class="mini-photo"></i><i class="mini-photo"></i><i class="mini-photo"></i></span><span class="month-meta"><b>${String(ch.number).padStart(2,'0')}</b><small>${ch.title}</small></span>`;b.onclick=()=>selectChapter(i);$('#months-nav').appendChild(b)})}
function selectChapter(i){chapterIndex=i;photoIndex=0;$$('.month-card').forEach((b,n)=>b.classList.toggle('active',n===i));$$('.month-card')[i].scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'});renderPhoto()}
function renderPhoto(){const ch=chapters[chapterIndex],p=ch.photos[photoIndex],img=$('#main-photo'),fallback=$('#photo-fallback');$('#chapter-number').textContent=`CAPÍTULO ${String(ch.number).padStart(2,'0')}`;$('#chapter-title').textContent=ch.title;$('#photo-count').textContent=`${String(photoIndex+1).padStart(2,'0')} / ${String(ch.photos.length).padStart(2,'0')}`;$('#photo-note').textContent=p.note;$('#photo-date').textContent=ch.date;$('#fallback-path').textContent=p.src;img.style.display='none';fallback.style.display='grid';img.onload=()=>{img.style.display='block';fallback.style.display='none'};img.onerror=()=>{img.style.display='none';fallback.style.display='grid'};img.src=p.src;$('#thumbnails').innerHTML='';ch.photos.forEach((photo,n)=>{const b=document.createElement('button');b.className='thumbnail'+(n===photoIndex?' active':'');const t=new Image;t.onload=()=>b.style.background=`url('${photo.src}') center/cover`;t.src=photo.src;b.onclick=()=>{photoIndex=n;renderPhoto()};$('#thumbnails').appendChild(b)})}
function movePhoto(s){photoIndex=(photoIndex+s+chapters[chapterIndex].photos.length)%chapters[chapterIndex].photos.length;renderPhoto()}
function visibleSongs(){return localStorage.getItem('giftUnlocked')==='yes'?[...songs,secretSong]:songs}
function renderSongList(){const box=$('#song-list');box.innerHTML='';visibleSongs().forEach((s,i)=>{const b=document.createElement('button');b.className='song-row'+(i===songIndex?' active':'');b.innerHTML=`<span>${s.icon}</span><span><b>${s.title}</b><small>${s.artist}</small></span><em>${s.secret?'NUEVA':'REPRODUCIR'}</em>`;b.onclick=()=>{loadSong(i,true);closeQueue()};box.appendChild(b)});if(localStorage.getItem('giftUnlocked')!=='yes'){const d=document.createElement('div');d.className='song-row locked';d.innerHTML='<span>🔒</span><span><b>Canción secreta</b><small>Encuentra el regalo escondido</small></span>';box.appendChild(d)}}
function loadSong(i,autoplay=false){const list=visibleSongs();songIndex=(i+list.length)%list.length;const s=list[songIndex];$('#song-title').textContent=s.title;$('#artist-name').textContent=s.artist;$('#album-art').textContent=s.icon;audio.pause();setPlayState(false);$('#progress-bar').value=0;$('#current-time').textContent='0:00';$('#duration-time').textContent='0:00';audio.src=s.src;audio.load();renderSongList();if(autoplay)playCurrent()}
function playCurrent(){const s=visibleSongs()[songIndex];audio.play().then(()=>setPlayState(true)).catch(()=>{setPlayState(false);appendMessage('Todavía falta agregar este archivo: '+s.src,'bot')})}
function togglePlay(){if(isPlaying){audio.pause();setPlayState(false)}else playCurrent()}function setPlayState(v){isPlaying=v;$('#btn-play').textContent=v?'Ⅱ':'▶';$('#record').classList.toggle('spinning',v)}
function nextSong(step=1){const list=visibleSongs();loadSong(shuffle?Math.floor(Math.random()*list.length):(songIndex+step+list.length)%list.length,true)}function formatTime(v){return Number.isFinite(v)?`${Math.floor(v/60)}:${String(Math.floor(v%60)).padStart(2,'0')}`:'0:00'}
function openQueue(){$('#song-menu').hidden=false;renderSongList()}function closeQueue(){$('#song-menu').hidden=true}
const starter=[{q:'te amo',a:'yo te amo más boba, muchísimo más ❤️'},{q:'quien eres',a:'soy un pedacito de Brian que dejó aquí para acompañarte jijiji'},{q:'cuanto me amas',a:'un montón que ni entra en estos 21 meses, rata ❤️'},{q:'te extraño',a:'yo también te extraño boba, ven pues 😭❤️'}];
function ownTraining(){try{return JSON.parse(localStorage.getItem('brianTraining')||'[]')}catch{return[]}}function normalize(t){return t.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9 ]/g,' ').trim()}
function botReply(text){const clean=normalize(text);let best=null,score=0;for(const e of [...starter,...ownTraining()]){const words=normalize(e.q).split(/\s+/).filter(w=>w.length>2),hits=words.filter(w=>clean.includes(w)).length,current=words.length?hits/words.length:0;if(current>score){score=current;best=e}}if(best&&score>=.5)return best.a;if(/foto|recuerdo/.test(clean))return`Esta es la foto ${photoIndex+1} del mes ${chapterIndex+1}. Brian dejó escrito: “${chapters[chapterIndex].photos[photoIndex].note}” ❤️`;if(/cancion|musica/.test(clean))return`Ahora está “${visibleSongs()[songIndex].title}”. Hay recuerdos que también suenan, no solo se miran.`;return'Jajaja todavía no sé cómo responder eso como Brian. Él puede enseñarme con “＋ enseñar” ❤️'}
function appendMessage(text,sender,extra=''){const d=document.createElement('div');d.className=`message ${sender}-message ${extra}`;d.textContent=text;$('#chat-messages').appendChild(d);$('#chat-messages').scrollTop=$('#chat-messages').scrollHeight;return d}function sendMessage(text){if(!text.trim())return;appendMessage(text,'user');const t=appendMessage('pensando como Brian…','bot','typing');setTimeout(()=>{t.remove();appendMessage(botReply(text),'bot')},550)}
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function renderTraining(){const own=ownTraining(),box=$('#training-list');box.innerHTML=own.length?'<span class="eyebrow">LO QUE YA APRENDÍ</span>':'';own.forEach((e,i)=>{const d=document.createElement('div');d.className='training-item';d.innerHTML=`<button>×</button><b>“${escapeHtml(e.q)}”</b><br>${escapeHtml(e.a)}`;d.querySelector('button').onclick=()=>{own.splice(i,1);localStorage.setItem('brianTraining',JSON.stringify(own));renderTraining()};box.appendChild(d)})}
function unlockGift(){localStorage.setItem('giftUnlocked','yes');$('#gift-lock').hidden=true;$('#gift-win').hidden=false;renderSongList();confetti();loadSong(visibleSongs().length-1,true)}function showGift(){const u=localStorage.getItem('giftUnlocked')==='yes';$('#gift-lock').hidden=u;$('#gift-win').hidden=!u;$('#gift-dialog').showModal()}
function confetti(){const box=$('#confetti');box.innerHTML='';for(let i=0;i<55;i++){const p=document.createElement('i');p.textContent=i%4?'✦':'♥';p.style.left=Math.random()*100+'vw';p.style.color=['#ef7ca4','#f4c66e','#fff0f3','#b96bb7'][i%4];p.style.animationDelay=Math.random()*.8+'s';p.style.setProperty('--drift',(Math.random()*160-80)+'px');box.appendChild(p)}setTimeout(()=>box.innerHTML='',4200)}
function bind(){$('#photo-prev').onclick=()=>movePhoto(-1);$('#photo-next').onclick=()=>movePhoto(1);$('#btn-play').onclick=togglePlay;$('#btn-next').onclick=()=>nextSong(1);$('#btn-prev').onclick=()=>nextSong(-1);$('#btn-shuffle').onclick=()=>{shuffle=!shuffle;$('#btn-shuffle').classList.toggle('active',shuffle)};$('#btn-loop').onclick=()=>{repeatMode=(repeatMode+1)%3;$('#btn-loop').classList.toggle('active',repeatMode>0);$('#btn-loop').textContent=repeatMode===2?'↻¹':'↻'};$('#volume').oninput=e=>audio.volume=e.target.value;$('#progress-bar').oninput=e=>{if(audio.duration)audio.currentTime=audio.duration*e.target.value/100};audio.ontimeupdate=()=>{$('#current-time').textContent=formatTime(audio.currentTime);$('#duration-time').textContent=formatTime(audio.duration);if(audio.duration)$('#progress-bar').value=audio.currentTime/audio.duration*100};audio.onended=()=>{if(repeatMode===2){audio.currentTime=0;playCurrent()}else if(shuffle||songIndex<visibleSongs().length-1||repeatMode===1){nextSong()}else{setPlayState(false)}};audio.onpause=()=>setPlayState(false);audio.onplay=()=>setPlayState(true);audio.volume=.8;$('#queue-toggle').onclick=()=>$('#song-menu').hidden?openQueue():closeQueue();$('#queue-close').onclick=closeQueue;
$('#chat-form').onsubmit=e=>{e.preventDefault();sendMessage($('#user-input').value);$('#user-input').value=''};$$('.quick-prompts button').forEach(b=>b.onclick=()=>sendMessage(b.dataset.prompt));$('#trainer-open').onclick=()=>{renderTraining();$('#trainer-dialog').showModal()};$('#trainer-form').onsubmit=e=>{e.preventDefault();const own=ownTraining();own.push({q:$('#training-input').value.trim(),a:$('#training-answer').value.trim()});localStorage.setItem('brianTraining',JSON.stringify(own));e.target.reset();renderTraining()};$('#gift-open').onclick=showGift;$('#gift-form').onsubmit=e=>{e.preventDefault();if($('#gift-password').value==='050124')unlockGift();else{$('#gift-error').textContent='Esa no es nuestra fecha… intenta otra vez ♡';$('#gift-password').select()}};$('#play-secret').onclick=()=>{loadSong(visibleSongs().length-1,true);$('#gift-dialog').close()};$$('[data-close]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).close());let x=0;$('#main-photo-wrap').ontouchstart=e=>x=e.changedTouches[0].clientX;$('#main-photo-wrap').ontouchend=e=>{const d=e.changedTouches[0].clientX-x;if(Math.abs(d)>45)movePhoto(d>0?-1:1)}}
createMonthCards();renderPhoto();loadSong(0);bind();
